-- ============================================================
-- 08 · DELIVERY · Orden global (reemplaza al 05)
--   Incluye Gyoza chiken teriyaki, Harumakis tonkatsu, y el
--   bloque de cocina Yakimeshis/Yakisobas + Tonkatsu (tras
--   Niguiris, antes de bebidas). Correr al final. Solo 'orden'.
-- ============================================================
begin;

update public.menu_items set orden=0 where tipo='delivery' and nombre='OTOÑO CON KIKU';
update public.menu_items set orden=1 where tipo='delivery' and nombre='OTOÑO CON KIKU II';
update public.menu_items set orden=2 where tipo='delivery' and nombre='4 Spicy roll';
update public.menu_items set orden=3 where tipo='delivery' and nombre='8 Spicy';
update public.menu_items set orden=4 where tipo='delivery' and nombre='2 Maki furai';
update public.menu_items set orden=5 where tipo='delivery' and nombre='4 Maki furai';
update public.menu_items set orden=6 where tipo='delivery' and nombre='2 Ranchero roll';
update public.menu_items set orden=7 where tipo='delivery' and nombre='4 Ranchero roll';
update public.menu_items set orden=8 where tipo='delivery' and nombre='2 Langostinos furai';
update public.menu_items set orden=9 where tipo='delivery' and nombre='4 Langostinos furai';
update public.menu_items set orden=10 where tipo='delivery' and nombre='6 Langostinos furai';
update public.menu_items set orden=11 where tipo='delivery' and nombre='Oniguiri furai';
update public.menu_items set orden=12 where tipo='delivery' and nombre='Dupla furai';
update public.menu_items set orden=13 where tipo='delivery' and nombre='Harumakis de carne';
update public.menu_items set orden=14 where tipo='delivery' and nombre='Harumakis veggie';
update public.menu_items set orden=15 where tipo='delivery' and nombre='Harumakis tonkatsu';
update public.menu_items set orden=16 where tipo='delivery' and nombre='Gyozas acevichadas';
update public.menu_items set orden=17 where tipo='delivery' and nombre='Gyozas de langostinos';
update public.menu_items set orden=18 where tipo='delivery' and nombre='Gyozas tako';
update public.menu_items set orden=19 where tipo='delivery' and nombre='Gyozas de ternera';
update public.menu_items set orden=20 where tipo='delivery' and nombre='Gyozas de cerdo';
update public.menu_items set orden=21 where tipo='delivery' and nombre='Gyozas veggie';
update public.menu_items set orden=22 where tipo='delivery' and nombre='Gyozas chiken teriyaki';
update public.menu_items set orden=23 where tipo='delivery' and nombre='Korokke de salmón';
update public.menu_items set orden=24 where tipo='delivery' and nombre='Korokke de pulpo';
update public.menu_items set orden=25 where tipo='delivery' and nombre='Korokke de shitake';
update public.menu_items set orden=26 where tipo='delivery' and nombre='Ceviche de pesca blanca';
update public.menu_items set orden=27 where tipo='delivery' and nombre='5 Ebi roll';
update public.menu_items set orden=28 where tipo='delivery' and nombre='9 Ebi roll';
update public.menu_items set orden=29 where tipo='delivery' and nombre='5 Philadelphia roll';
update public.menu_items set orden=30 where tipo='delivery' and nombre='9 Philadelphia roll';
update public.menu_items set orden=31 where tipo='delivery' and nombre='5 Ahumado roll';
update public.menu_items set orden=32 where tipo='delivery' and nombre='9 Ahumado roll';
update public.menu_items set orden=33 where tipo='delivery' and nombre='5 New York roll';
update public.menu_items set orden=34 where tipo='delivery' and nombre='9 New York';
update public.menu_items set orden=35 where tipo='delivery' and nombre='9 Sake roll';
update public.menu_items set orden=36 where tipo='delivery' and nombre='5 Sake roll';
update public.menu_items set orden=37 where tipo='delivery' and nombre='5 Guacamole roll';
update public.menu_items set orden=38 where tipo='delivery' and nombre='9 Guacamole roll';
update public.menu_items set orden=39 where tipo='delivery' and nombre='5 Acevichado roll';
update public.menu_items set orden=40 where tipo='delivery' and nombre='9 Acevichado roll';
update public.menu_items set orden=41 where tipo='delivery' and nombre='5 Nikkei roll';
update public.menu_items set orden=42 where tipo='delivery' and nombre='9 Nikkei roll';
update public.menu_items set orden=43 where tipo='delivery' and nombre='5 Fancy roll';
update public.menu_items set orden=44 where tipo='delivery' and nombre='9 Fancy roll';
update public.menu_items set orden=45 where tipo='delivery' and nombre='5 Phila Nipon roll';
update public.menu_items set orden=46 where tipo='delivery' and nombre='9 Phila Nipon roll';
update public.menu_items set orden=47 where tipo='delivery' and nombre='5 Ahumado de maracuyá roll';
update public.menu_items set orden=48 where tipo='delivery' and nombre='9 Ahumado de maracuyá roll';
update public.menu_items set orden=49 where tipo='delivery' and nombre='5 Tempura roll';
update public.menu_items set orden=50 where tipo='delivery' and nombre='9 Tempura roll';
update public.menu_items set orden=51 where tipo='delivery' and nombre='5 Tartar sake roll';
update public.menu_items set orden=52 where tipo='delivery' and nombre='9 Tartar sake roll';
update public.menu_items set orden=53 where tipo='delivery' and nombre='4 Tamago roll';
update public.menu_items set orden=54 where tipo='delivery' and nombre='8 Tamago roll';
update public.menu_items set orden=55 where tipo='delivery' and nombre='8 Tamago ebi furai roll';
update public.menu_items set orden=56 where tipo='delivery' and nombre='9 Huanca Roll';
update public.menu_items set orden=57 where tipo='delivery' and nombre='9 Ebi mango roll';
update public.menu_items set orden=58 where tipo='delivery' and nombre='9 Sake Acevichado roll';
update public.menu_items set orden=59 where tipo='delivery' and nombre='9 Tex ebi roll';
update public.menu_items set orden=60 where tipo='delivery' and nombre='9 Ceviche roll';
update public.menu_items set orden=61 where tipo='delivery' and nombre='9 Bajiru Roll';
update public.menu_items set orden=62 where tipo='delivery' and nombre='8 Tamago palta roll';
update public.menu_items set orden=63 where tipo='delivery' and nombre='9 Maki vegan roll';
update public.menu_items set orden=64 where tipo='delivery' and nombre='Kiku 12 pzas';
update public.menu_items set orden=65 where tipo='delivery' and nombre='Kiku 15 pzas';
update public.menu_items set orden=66 where tipo='delivery' and nombre='Fusión 12 pzas';
update public.menu_items set orden=67 where tipo='delivery' and nombre='Fusión 15 pzas';
update public.menu_items set orden=68 where tipo='delivery' and nombre='Nikkei 12 pzas';
update public.menu_items set orden=69 where tipo='delivery' and nombre='Nikkei 15 pzas';
update public.menu_items set orden=70 where tipo='delivery' and nombre='Exotic 12 pzas';
update public.menu_items set orden=71 where tipo='delivery' and nombre='Exotic 15 pzas';
update public.menu_items set orden=72 where tipo='delivery' and nombre='Veggie 15 pzas';
update public.menu_items set orden=73 where tipo='delivery' and nombre='2 Geishas de Salmón';
update public.menu_items set orden=74 where tipo='delivery' and nombre='6 geishas de salmón';
update public.menu_items set orden=75 where tipo='delivery' and nombre='2 geishas de salmón ahumado';
update public.menu_items set orden=76 where tipo='delivery' and nombre='6 geishas de salmón ahumado';
update public.menu_items set orden=77 where tipo='delivery' and nombre='2 geishas queens';
update public.menu_items set orden=78 where tipo='delivery' and nombre='6 geishas queen';
update public.menu_items set orden=79 where tipo='delivery' and nombre='2 Sashimis de salmón';
update public.menu_items set orden=80 where tipo='delivery' and nombre='5 sashimi de salmón';
update public.menu_items set orden=81 where tipo='delivery' and nombre='2 sashimi tako';
update public.menu_items set orden=82 where tipo='delivery' and nombre='5 sashimi tako';
update public.menu_items set orden=83 where tipo='delivery' and nombre='2 sashimis tatakis';
update public.menu_items set orden=84 where tipo='delivery' and nombre='5 sashimi tataki';
update public.menu_items set orden=85 where tipo='delivery' and nombre='2 sashimi tataki thai';
update public.menu_items set orden=86 where tipo='delivery' and nombre='5 sashimi tataki thai';
update public.menu_items set orden=87 where tipo='delivery' and nombre='2 tiradito nipón';
update public.menu_items set orden=88 where tipo='delivery' and nombre='5 tiradito nipón';
update public.menu_items set orden=89 where tipo='delivery' and nombre='2 tiradito maracuyá';
update public.menu_items set orden=90 where tipo='delivery' and nombre='5 tiradito maracuyá';
update public.menu_items set orden=91 where tipo='delivery' and nombre='2 Niguiri de salmón';
update public.menu_items set orden=92 where tipo='delivery' and nombre='6 Niguiri de salmón';
update public.menu_items set orden=93 where tipo='delivery' and nombre='2 Niguiri de Salmón Tataki Thai';
update public.menu_items set orden=94 where tipo='delivery' and nombre='6 Niguiri de Salmón Tataki Thai';
update public.menu_items set orden=95 where tipo='delivery' and nombre='2 Niguiri tako';
update public.menu_items set orden=96 where tipo='delivery' and nombre='6 Niguiri tako';
update public.menu_items set orden=97 where tipo='delivery' and nombre='Yakimeshi Veggie';
update public.menu_items set orden=98 where tipo='delivery' and nombre='Yakimeshi Cerdo';
update public.menu_items set orden=99 where tipo='delivery' and nombre='Yakimeshi de Langostinos';
update public.menu_items set orden=100 where tipo='delivery' and nombre='Yakisoba Veggie';
update public.menu_items set orden=101 where tipo='delivery' and nombre='Yakisoba de Cerdo';
update public.menu_items set orden=102 where tipo='delivery' and nombre='Yakisoba de Langostinos';
update public.menu_items set orden=103 where tipo='delivery' and nombre='Tonkatsu';
update public.menu_items set orden=104 where tipo='delivery' and nombre='Coca cola lata';
update public.menu_items set orden=105 where tipo='delivery' and nombre='Coca cola zero lata';
update public.menu_items set orden=106 where tipo='delivery' and nombre='Sprite lata';
update public.menu_items set orden=107 where tipo='delivery' and nombre='Vaso de limonada';
update public.menu_items set orden=108 where tipo='delivery' and nombre='Cerveza Heineken 330ml';
update public.menu_items set orden=109 where tipo='delivery' and nombre='Cerveza Corona 330ml';
update public.menu_items set orden=110 where tipo='delivery' and nombre='Cerveza Sapporo 330ml';
update public.menu_items set orden=111 where tipo='delivery' and nombre='Cerveza Tsingtao 330ml';
update public.menu_items set orden=112 where tipo='delivery' and nombre='Cerveza Orion Lata';
update public.menu_items set orden=113 where tipo='delivery' and nombre='Las Perdices Torrontés Dulce Natural';
update public.menu_items set orden=114 where tipo='delivery' and nombre='Chac Chac Malbec Rosé';
update public.menu_items set orden=115 where tipo='delivery' and nombre='Las Perdices Reserva Malbec';
update public.menu_items set orden=116 where tipo='delivery' and nombre='Las Perdices Reserva Sauvignon Blanc';
update public.menu_items set orden=117 where tipo='delivery' and nombre='Las Perdices Reserva Pinot Noir';
update public.menu_items set orden=118 where tipo='delivery' and nombre='Riesling de Viña Las Perdices';
update public.menu_items set orden=119 where tipo='delivery' and nombre='Albariño de Viña Las Perdices';
update public.menu_items set orden=120 where tipo='delivery' and nombre='Las Perdices Extra Brut Método Tradicional';
update public.menu_items set orden=121 where tipo='delivery' and nombre='Salentein Reserva Chardonnay';
update public.menu_items set orden=122 where tipo='delivery' and nombre='Salentein Reserva Sauvignon Blanc';
update public.menu_items set orden=123 where tipo='delivery' and nombre='Salentein Reserva Malbec';
update public.menu_items set orden=124 where tipo='delivery' and nombre='Salentein Brut Nature';
update public.menu_items set orden=125 where tipo='delivery' and nombre='Salentein Brut Rosé';
update public.menu_items set orden=126 where tipo='delivery' and nombre='Salentein Extra Brut';
update public.menu_items set orden=127 where tipo='delivery' and nombre='Salentein Blanc de Blancs';
update public.menu_items set orden=128 where tipo='delivery' and nombre='Salentein Doux';
update public.menu_items set orden=129 where tipo='delivery' and nombre='Escorihuela Gascón Sauvignon Blanc';
update public.menu_items set orden=130 where tipo='delivery' and nombre='Escorihuela Gascón Chardonnay';
update public.menu_items set orden=131 where tipo='delivery' and nombre='Escorihuela Gascón Malbec';
update public.menu_items set orden=132 where tipo='delivery' and nombre='Luigi Bosca Chardonnay';
update public.menu_items set orden=133 where tipo='delivery' and nombre='Luigi Bosca Sauvignon Blanc';
update public.menu_items set orden=134 where tipo='delivery' and nombre='Luigi Bosca Rosé';
update public.menu_items set orden=135 where tipo='delivery' and nombre='DV Catena Chardonnay';
update public.menu_items set orden=136 where tipo='delivery' and nombre='Rutini Wines Sauvignon Blanc';
update public.menu_items set orden=137 where tipo='delivery' and nombre='Rutini Malbec';
update public.menu_items set orden=138 where tipo='delivery' and nombre='Rutini Encuentro Brut Nature Pinot Noir';

commit;