-- ============================================================
-- Importacion de carta DELIVERY - Kiku Sushi
-- Productos: 116
-- Ejecutar en: Supabase -> SQL Editor -> New query -> Run
-- imagen_url -> bucket menu-images/delivery/<slug>.jpg
-- ============================================================

begin;

-- ------------------------------------------------------------
-- REEMPLAZO SEGURO de la carta delivery anterior.
-- (Si solo queres AGREGAR sin tocar lo existente, borra estas dos sentencias.)
-- No se pueden borrar items con pedidos (FK pedido_items):
--   1) ocultamos los referenciados (preserva historial)
--   2) borramos solo los no referenciados
-- ------------------------------------------------------------
update public.menu_items
   set activo = false
 where tipo = 'delivery'
   and id in (select menu_item_id from public.pedido_items where menu_item_id is not null);

delete from public.menu_items
 where tipo = 'delivery'
   and id not in (select menu_item_id from public.pedido_items where menu_item_id is not null);

insert into public.menu_items
  (tipo, categoria, subtitulo, nombre, descripcion, precio, etiqueta, activo, orden, imagen_url)
values
  ('delivery', 'Especiales de Temporada', NULL, 'OTOÑO CON KIKU', '2 korokkes de degustación + 6 pzas de sushi omakase', 18000, NULL, true, 0, NULL),
  ('delivery', 'Especiales de Temporada', NULL, 'OTOÑO CON KIKU II', '2 langostinos furai + 6 pzas de sushi omakase + bebida (cerveza o gasesosa)', 20000, NULL, true, 1, NULL),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', '4 Spicy roll', '4 pzas de rebozado envuelto en arroz sin alga, relleno de salmón rosado, palta y queso. Coronado de mayonesa spicy.', 12100, NULL, true, 2, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/4-spicy-roll.jpg'),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', '8 Spicy', '8 pzas de roll rebozado envuelto en arroz sin alga, relleno de salmón rosado, palta y queso. Coronado de mayonesa spicy.', 17000, NULL, true, 3, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/8-spicy.jpg'),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', '2 Maki furai', '2 pzas de Maki de salmón, apanado y frito. Top de guacamole y vieiras rancheras.', 11200, NULL, true, 4, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-maki-furai.jpg'),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', '4 Maki furai', '4 pzas de Maki de salmón, apanado y frito. Top de guacamole y vieiras rancheras.', 17000, NULL, true, 5, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/4-maki-furai.jpg'),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', '2 Ranchero roll', '2 pzas de rebozado envuelto en arroz sin alga, relleno de salmón rosado, palta y queso. Coronado de langostinos picantes marinados sobre guacamole.', 12200, NULL, true, 6, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-ranchero-roll.jpg'),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', '4 Ranchero roll', '4 pzas de rebozado envuelto en arroz sin alga, relleno de salmón rosado, palta y queso. Coronado de langostinos picantes marinados sobre guacamole.', 17700, NULL, true, 7, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/4-ranchero-roll.jpg'),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', '2 Langostinos furai', '2 pzas de langostinos rebozados en panco y fritos. Acompañado de salsa agridulce de mostaza y miel.', 9000, NULL, true, 8, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-langostinos-furai.jpg'),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', '4 Langostinos furai', '4 pzas de langostinos rebozados en panco y fritos. Acompañado de salsa agridulce de mostaza y miel.', 14000, NULL, true, 9, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/4-langostinos-furai.jpg'),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', '6 Langostinos furai', '6 pzas de langostinos rebozados en panco y fritos. Acompañado de salsa agridulce de mostaza y miel.', 22000, NULL, true, 10, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/6-langostinos-furai.jpg'),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', 'Oniguiri furai', 'Dupla de triángulos de shari, envueltos en alga nori, rebozado en panco y frito, relleno de salmón cocido. Coronado de mayo japo y salsa brava.', 16000, NULL, true, 11, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/oniguiri-furai.jpg'),
  ('delivery', 'Rebozados', 'Apanados en panco y fritos', 'Dupla furai', 'Dupla de un ceviche de vieiras y maíz chulpi. Un tartar de salmón sobre colchón de shari furai.', 17000, NULL, true, 12, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/dupla-furai.jpg'),
  ('delivery', 'Harumakis', NULL, 'Harumakis de carne', '4 unidades de arrollados primavera de carne fritos. Acompañado de salsa china agridulce.', 10500, NULL, true, 13, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/harumakis-de-carne.jpg'),
  ('delivery', 'Harumakis', NULL, 'Harumakis veggie', '4 unidades de arrollados primavera de vegetales (zanahoria, repollo, cebolla) fritos. Acompañado de salsa china agridulce.', 10500, NULL, true, 14, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/harumakis-veggie.jpg'),
  ('delivery', 'Gyozas', NULL, 'Gyozas acevichadas', '4 unidades de empanadillas japonesas fritas, rellenas de pesca blanca, cebolla morada y cilantro. Fritas, acompañadas de salsa tonkatsu.', 12900, NULL, true, 15, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/gyozas-acevichadas.jpg'),
  ('delivery', 'Gyozas', NULL, 'Gyozas de langostinos', '4 unidades de empanadillas de trigo japonesas, relleno de langostinos al curry. Selladas y al vapor. Acompañado de salsa china agridulce.', 12900, NULL, true, 16, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/gyozas-de-langostinos.jpg'),
  ('delivery', 'Gyozas', NULL, 'Gyozas tako', '4 unidades de empanadillas de trigo japonesas, relleno de vegetales y pulpo. Selladas y al vapor. Acompañado de salsa china agridulce.', 12000, NULL, true, 17, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/gyozas-tako.jpg'),
  ('delivery', 'Gyozas', NULL, 'Gyozas de ternera', '4 unidades de empanadillas de trigo japonesas, relleno de ternera. Selladas y al vapor. Acompañado de salsa de soja cítrica.', 12500, NULL, true, 18, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/gyozas-de-ternera.jpg'),
  ('delivery', 'Gyozas', NULL, 'Gyozas de cerdo', '4 unidades de empanadillas de trigo japonesas, relleno de carne de cerdo. Selladas y al vapor. Acompañado de salsa china agridulce.', 12000, NULL, true, 19, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/gyozas-de-cerdo.jpg'),
  ('delivery', 'Gyozas', NULL, 'Gyozas veggie', '4 unidades de empanadillas de trigo japonesas, relleno de vegetales. Selladas y al vapor. Acompañado de salsa china agridulce.', 11000, NULL, true, 20, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/gyozas-veggie.jpg'),
  ('delivery', 'Korokkes', NULL, 'Korokke de salmón', '2 unidades de croquetas japonesas rellenas de puerro, salsa blanca y salmón. Acompañado de salsa brava', 16000, NULL, true, 21, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/korokke-de-salmon.jpg'),
  ('delivery', 'Korokkes', NULL, 'Korokke de pulpo', '2 unidades de croquetas japonesas rellenas de puerro, salsa blanca y pulpo. Acompañado de salsa brava.', 17000, NULL, true, 22, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/korokke-de-pulpo.jpg'),
  ('delivery', 'Korokkes', NULL, 'Korokke de shitake', '2 unidades de croquetas japonesas rellenas de puerro, salsa blanca y shitake. Acompañado de salsa brava', 14000, NULL, true, 23, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/korokke-de-shitake.jpg'),
  ('delivery', 'Ceviches', NULL, 'Ceviche de pesca blanca', 'Marinada de pesca blanca en leche de tigre. Coronado con maiz peruano morado, plátano frito, maiz chulpi, cebolla morada y ajies.', 19500, NULL, true, 24, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/ceviche-de-pesca-blanca.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Ebi roll', 'Relleno de salmón, queso, palta y langostinos. Envuelto en alga nori y arroz. Semicubierto de lámina de salmón, bañado en salsa acevichada y top de huevas de salmón.', 13300, NULL, true, 25, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-ebi-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Ebi roll', 'Relleno de salmón, queso, palta y langostinos. Envuelto en alga nori y arroz. Semicubierto de lámina de salmón, bañado en salsa acevichada y top de huevas de salmón.', 23200, NULL, true, 26, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-ebi-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Philadelphia roll', 'Relleno de salmón y queso. Envuelto en alga nori y arroz. Cubierto de sésamo blanco.', 12800, NULL, true, 27, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-philadelphia-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Ahumado roll', 'Roll relleno de salmón ahumado, palta y queso. Envuelto en alga nori y arroz. Semicubierto de lámina de salmón rosado. Bañado en salsa de sésamo.', 13200, NULL, true, 28, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-ahumado-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Ahumado roll', 'Roll relleno de salmón ahumado, palta y queso. Envuelto en alga nori y arroz. Semicubierto de lámina de salmón rosado. Bañado en salsa de sésamo.', 22900, NULL, true, 29, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-ahumado-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 New York roll', 'Relleno de salmón y palta. Envuelto en alga nori y arroz. Cubierto de sésamo negro.', 13300, NULL, true, 30, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-new-york-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 New York', 'Relleno de salmón y palta. Envuelto en alga nori y arroz. Cubierto de sésamo negro.', 23300, NULL, true, 31, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-new-york.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Sake roll', 'Roll relleno de salmón rosado al verdeo. Envuelto en alga nori y arroz. Cubierto de ciboulette, bañado con salsa teriyaki.', 22200, NULL, true, 32, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-sake-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Sake roll', 'Roll relleno de salmón rosado al verdeo. Envuelto en alga nori y arroz. Cubierto de ciboulette, bañado con salsa teriyaki.', 13200, NULL, true, 33, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-sake-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Guacamole roll', 'Langostinos furai y queso miso. Envuelto en alga nori y arroz. Coronado de guacamole de palta.', 12800, NULL, true, 34, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-guacamole-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Guacamole roll', 'Langostinos furai y queso miso. Envuelto en alga nori y arroz. Coronado de guacamole de palta.', 22200, NULL, true, 35, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-guacamole-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Acevichado roll', 'Langostinos furai y queso miso. Envuelto en alga nori y arroz. Coronado de ceviche de salmón y maíz chulpi.', 12800, NULL, true, 36, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-acevichado-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Acevichado roll', 'Langostinos furai y queso miso. Envuelto en alga nori y arroz. Coronado de ceviche de salmón y maíz chulpi.', 22000, NULL, true, 37, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-acevichado-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Nikkei roll', 'Langostinos furai y palta. Envuelto en alga y arroz. Con un top de tartar de pulpo', 14900, NULL, true, 38, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-nikkei-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Nikkei roll', 'Langostinos furai y palta. Envuelto en alga nori y arroz. Coronado de tartar de pulpo.', 27800, NULL, true, 39, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-nikkei-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Fancy roll', 'Salmón, queso y frutilla. Envuelto en alga nori y arroz. Bañado con salsa teriyaki', 12800, NULL, true, 40, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-fancy-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Fancy roll', 'Salmón, queso y frutilla. Envuelto en alga nori y arroz. Bañado con salsa teriyaki.', 22200, NULL, true, 41, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-fancy-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Phila Nipon roll', 'Salmón rosado, palta y queso. Coronado de chimi nipón.', 12800, NULL, true, 42, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-phila-nipon-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Phila Nipon roll', 'Salmón rosado, palta y queso. Coronado de chimi nipón.', 22200, NULL, true, 43, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-phila-nipon-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Ahumado de maracuyá roll', 'Salmón ahumado, queso y rúcula. Envuelto en alga nori y arroz. Semicubierto de salmón. Bañado en salsa maracuyá.', 14500, NULL, true, 44, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-ahumado-de-maracuya-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Ahumado de maracuyá roll', 'Salmón ahumado, queso y rúcula. Envuelto en alga nori y arroz. Semicubierto de salmón. Bañado en salsa maracuyá.', 23200, NULL, true, 45, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-ahumado-de-maracuya-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Tempura roll', 'Langostinos en tempura, tamago y queso cítrico. Envuelto en alga nori y arroz. Semicubierto de lámina de salmón, bañado en salsa acevichada. Espolvoreado con togarashi.', 12800, NULL, true, 46, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-tempura-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Tempura roll', 'Langostinos en tempura, tamago y queso cítrico. Envuelto en alga nori y arroz. Semicubierto de lámina de salmón, bañado en salsa acevichada. Espolvoreado con togarashi.', 22200, NULL, true, 47, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-tempura-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '5 Tartar sake roll', 'Langostinos en tempura, tamago y queso cítrico. Envuelto en alga nori y arroz. Coronado de tartar de salmón rosado y cebolla crispy.', 12800, NULL, true, 48, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-tartar-sake-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Tartar sake roll', 'Langostinos en tempura, tamago y queso cítrico. Envuelto en alga nori y arroz. Coronado de tartar de salmón rosado y cebolla crispy', 22200, NULL, true, 49, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-tartar-sake-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '4 Tamago roll', 'Queso, palmitos y salmon. Envuelto en lamina de tamago. Coronado en salsa maracuya. Topp de hilos de boniato frito.', 9000, NULL, true, 50, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/4-tamago-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '8 Tamago roll', 'Queso, palmitos y salmon. Envuelto en lamina de tamago. Coronado en salsa maracuya. Topp de hilos de boniato frito.', 16000, NULL, true, 51, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/8-tamago-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '8 Tamago ebi furai roll', 'Queso citrico y ebi furai. Envuelto en lamina de tamago. Coronado en salsa maracuya. Topp de hilos de boniato frito.', 16500, NULL, true, 52, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/8-tamago-ebi-furai-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Huanca Roll', 'Langostinos furai y palta. Semicubierto se salmón. Coronado en salsa huancaina y polvo de aceituna.', 16000, NULL, true, 53, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-huanca-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Ebi mango roll', 'Langostinos rancheros, mango y queso. Envuelto en alga nori y arroz. Semicubierto de salmón rosado. Bañado con salsa agridulce.', 22200, NULL, true, 54, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-ebi-mango-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Sake Acevichado roll', 'Rebozado de pescado blanco y palta. Semicubierto de tataki de salmón rosado, bañado en salsa acevichada. Top de chicharrón de pescado blanco.', 27600, NULL, true, 55, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-sake-acevichado-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Tex ebi roll', 'Langostinos en tempura, queso y pepino en juliana. Bañado en salsa acevichada y polvo de crocante de maíz.', 23300, NULL, true, 56, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-tex-ebi-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Ceviche roll', 'Langostinos furai y queso miso. Envuelto en alga nori y arroz. Top de crocante de maíz. Coronado con ceviche de pescado blanco y vieiras.', 23300, NULL, true, 57, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-ceviche-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Maki vegan roll', 'Roll de arroz relleno de guacamole y espinaca, cubierto de alga nori. Con top de tartar vegano (mayonesa spicy y chauchas).', 17000, NULL, true, 58, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-maki-vegan-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '8 Tamago palta roll', 'Queso, palmito y palta. Envuelto en lamina de tamago. Salsa maracuyá, coronado de hilos de boniato frito', 16000, NULL, true, 59, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/8-tamago-palta-roll.jpg'),
  ('delivery', 'Rollos de Sushi', NULL, '9 Bajiru Roll', 'Roll relleno de queso, mix de tomates confitados y albahaca fresca. Envuelto en arroz y alga nori. Acompañado de mayonesa de olivo trufada.', 16500, NULL, true, 60, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/9-bajiru-roll.jpg'),
  ('delivery', 'Combinados Kiku', NULL, 'Kiku 12 pzas', 'Sin sashimi • Ebi Roll | Philadelphia Roll | Ahumado Roll |New York Roll', 31900, NULL, true, 61, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/kiku-12-pzas.jpg'),
  ('delivery', 'Combinados Kiku', NULL, 'Kiku 15 pzas', 'Ebi Roll | Philadelphia Roll | Ahumado Roll |New York Roll | Sashimi', 34600, NULL, true, 62, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/kiku-15-pzas.jpg'),
  ('delivery', 'Combinados Fusión', NULL, 'Fusión 12 pzas', 'Sin tiradito de Salmón • Sake Roll | Tartar Sake Roll | Guacamole Roll | Ebi Roll | Spicy Roll', 30200, NULL, true, 63, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/fusion-12-pzas.jpg'),
  ('delivery', 'Combinados Fusión', NULL, 'Fusión 15 pzas', 'Tiradito de Salmón | Sake Roll | Tartar Sake Roll | Guacamole Roll | Ebi Roll | Spicy Roll', 31700, NULL, true, 64, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/fusion-15-pzas.jpg'),
  ('delivery', 'Combinados Nikkei', NULL, 'Nikkei 12 pzas', 'Sin Tiradito de Pulpo • Sake Roll | Tempura Roll | Acevichado Roll | Ebi Roll | Nikkei Roll', 35000, NULL, true, 65, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/nikkei-12-pzas.jpg'),
  ('delivery', 'Combinados Nikkei', NULL, 'Nikkei 15 pzas', 'Tiradito de Pulpo | Sake Roll | Tempura Roll | Acevichado Roll | Ebi Roll | Nikkei Roll', 38000, NULL, true, 66, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/nikkei-15-pzas.jpg'),
  ('delivery', 'Combinados Exotic', NULL, 'Exotic 12 pzas', 'Phila Nipón Roll | Fancy Roll | Ebi Mango Roll | Niguiri Thai | Tiradito Nipón', 27600, NULL, true, 67, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/exotic-12-pzas.jpg'),
  ('delivery', 'Combinados Exotic', NULL, 'Exotic 15 pzas', 'Phila Nipón Roll | Fancy Roll | Ebi Mango Roll | Niguiri Thai | Tiradito Nipón', 34300, NULL, true, 68, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/exotic-15-pzas.jpg'),
  ('delivery', 'Combinados Veggie', NULL, 'Veggie 15 pzas', 'Ponzu Roll | Maki Vegan Roll | Bajiru | Arrolladitos Primavera', 24300, NULL, true, 69, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/veggie-15-pzas.jpg'),
  ('delivery', 'Geishas', NULL, '2 Geishas de Salmón', 'Láminas enrolladas de salmón rosado, queso y palta.', 9500, NULL, true, 70, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-geishas-de-salmon.jpg'),
  ('delivery', 'Geishas', NULL, '6 geishas de salmón', 'Láminas enrolladas de salmón rosado, queso y palta.', 17500, NULL, true, 71, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/6-geishas-de-salmon.jpg'),
  ('delivery', 'Geishas', NULL, '2 geishas de salmón ahumado', 'Láminas enrolladas de salmón ahumado, queso y palta.', 9500, NULL, true, 72, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-geishas-de-salmon-ahumado.jpg'),
  ('delivery', 'Geishas', NULL, '6 geishas de salmón ahumado', 'Láminas enrolladas de salmón ahumado, queso y palta.', 21200, NULL, true, 73, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/6-geishas-de-salmon-ahumado.jpg'),
  ('delivery', 'Geishas', NULL, '2 geishas queens', 'Láminas enrolladas de salmón rosado, queso y palta. Bañado en salsa maracuyá.', 10500, NULL, true, 74, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-geishas-queens.jpg'),
  ('delivery', 'Geishas', NULL, '6 geishas queen', 'Láminas enrolladas de salmón rosado, queso y palta. Bañado en salsa maracuyá.', 24000, NULL, true, 75, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/6-geishas-queen.jpg'),
  ('delivery', 'Sashimis', NULL, '2 Sashimis de salmón', 'Cortes de lomo de salmón rosado', 10500, NULL, true, 76, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-sashimis-de-salmon.jpg'),
  ('delivery', 'Sashimis', NULL, '5 sashimi de salmón', 'Cortes de lomo de salmón rosado.', 22000, NULL, true, 77, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-sashimi-de-salmon.jpg'),
  ('delivery', 'Sashimis', NULL, '2 sashimi tako', 'Cortes de pulpo bañado en salsa ponzu.', 13400, NULL, true, 78, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-sashimi-tako.jpg'),
  ('delivery', 'Sashimis', NULL, '5 sashimi tako', 'Cortes de pulpo bañado en salsa ponzu.', 26000, NULL, true, 79, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-sashimi-tako.jpg'),
  ('delivery', 'Sashimis', NULL, '2 sashimis tatakis', 'Cortes de lomo de salmón rosado sellado. Cubierto de sésamo negro y salsa ponzu.', 10500, NULL, true, 80, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-sashimis-tatakis.jpg'),
  ('delivery', 'Sashimis', NULL, '5 sashimi tataki', 'Cortes de lomo de salmón rosado sellado. Cubierto de sésamo negro y salsa ponzu.', 22000, NULL, true, 81, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-sashimi-tataki.jpg'),
  ('delivery', 'Sashimis', NULL, '2 sashimi tataki thai', 'Cortes de lomo de salmón. Bañado y sellado en salsa thai.', 12500, NULL, true, 82, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-sashimi-tataki-thai.jpg'),
  ('delivery', 'Sashimis', NULL, '5 sashimi tataki thai', 'Cortes de lomo de salmón. Bañado y sellado en salsa thai.', 22500, NULL, true, 83, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-sashimi-tataki-thai.jpg'),
  ('delivery', 'Tiraditos', NULL, '2 tiradito nipón', '2 pzas de láminas de salmón, acompañado de chimi nipón, espolvoreado de maíz cancha.', 10500, NULL, true, 84, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-tiradito-nipon.jpg'),
  ('delivery', 'Tiraditos', NULL, '5 tiradito nipón', '5 pzas de láminas de salmón, acompañado de chimi nipón, espolvoreado de maíz chulpi.', 19500, NULL, true, 85, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-tiradito-nipon.jpg'),
  ('delivery', 'Tiraditos', NULL, '2 tiradito maracuyá', '2 pzas de láminas de salmón, acompañado de salsa maracuyá. Coronado de plátano frito.', 11000, NULL, true, 86, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-tiradito-maracuya.jpg'),
  ('delivery', 'Tiraditos', NULL, '5 tiradito maracuyá', '5 pzas de láminas de salmón, acompañado de salsa maracuyá. Coronado de plátano frito.', 20000, NULL, true, 87, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/5-tiradito-maracuya.jpg'),
  ('delivery', 'Niguiris', NULL, '2 Niguiri de salmón', 'Bocado de arroz, cubierto por una lonja de salmón rosado.', 10000, NULL, true, 88, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-niguiri-de-salmon.jpg'),
  ('delivery', 'Niguiris', NULL, '6 Niguiri de salmón', 'Bocado de arroz, cubierto por una lonja de salmón rosado.', 20500, NULL, true, 89, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/6-niguiri-de-salmon.jpg'),
  ('delivery', 'Niguiris', NULL, '2 Niguiri de Salmón Tataki Thai', 'Bocado de arroz, cubierto por una lonja de salmón rosado. Sellado con salsa thai.', 10500, NULL, true, 90, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-niguiri-de-salmon-tataki-thai.jpg'),
  ('delivery', 'Niguiris', NULL, '6 Niguiri de Salmón Tataki Thai', 'Bocado de arroz, cubierto por una lonja de salmón rosado. Sellado con salsa thai.', 21000, NULL, true, 91, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/6-niguiri-de-salmon-tataki-thai.jpg'),
  ('delivery', 'Niguiris', NULL, '2 Niguiri tako', 'Bocado de arroz, cubierto por una lonja de pulpo. Acompañado de una mayonesa de olivo trufada.', 12200, NULL, true, 92, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/2-niguiri-tako.jpg'),
  ('delivery', 'Niguiris', NULL, '6 Niguiri tako', 'Bocado de arroz, cubierto por una lonja de pulpo. Acompañado de una mayonesa de olivo trufada.', 27000, NULL, true, 93, 'https://sepyieuxsmxhzobtmzxb.supabase.co/storage/v1/object/public/menu-images/delivery/6-niguiri-tako.jpg'),
  ('delivery', 'Bebidas sin alcohol', NULL, 'Agua c/gas', '', 3500, NULL, true, 94, NULL),
  ('delivery', 'Bebidas sin alcohol', NULL, 'Agua s/gas', '', 3800, NULL, true, 95, NULL),
  ('delivery', 'Bebidas sin alcohol', NULL, 'Coca cola lata', '', 4000, NULL, true, 96, NULL),
  ('delivery', 'Bebidas sin alcohol', NULL, 'Coca cola zero lata', '', 4000, NULL, true, 97, NULL),
  ('delivery', 'Bebidas sin alcohol', NULL, 'Sprite lata', '', 4000, NULL, true, 98, NULL),
  ('delivery', 'Cervezas', NULL, 'Cerveza Corona 330ml', '', 5500, NULL, true, 99, NULL),
  ('delivery', 'Cervezas', NULL, 'Cerveza Heineken 330ml', '', 6000, NULL, true, 100, NULL),
  ('delivery', 'Cervezas', NULL, 'Cerveza Sapporo 330ml', 'Japón', 9500, NULL, true, 101, NULL),
  ('delivery', 'Vinos Sauvignon Blanc', NULL, 'Salentein Reserva Sauvignon Blanc', '', 26500, NULL, true, 102, NULL),
  ('delivery', 'Vinos Sauvignon Blanc', NULL, 'Escorihuela Gascón Sauvignon Blanc', '', 27000, NULL, true, 103, NULL),
  ('delivery', 'Vinos Sauvignon Blanc', NULL, 'Luigi Bosca Sauvignon Blanc', '', 36000, NULL, true, 104, NULL),
  ('delivery', 'Vinos Chardonnay', NULL, 'Salentein Reserva Chardonnay', '', 26000, NULL, true, 105, NULL),
  ('delivery', 'Vinos Chardonnay', NULL, 'Escorihuela Gascón Chardonnay', '', 27000, NULL, true, 106, NULL),
  ('delivery', 'Vinos Chardonnay', NULL, 'DV Catena Chardonnay', '', 40000, NULL, true, 107, NULL),
  ('delivery', 'Vinos Rosados', NULL, 'Salentein Reserva Rosé', '', 24000, NULL, true, 108, NULL),
  ('delivery', 'Vinos Rosados', NULL, 'Familia Gascón Rosé', '', 24500, NULL, true, 109, NULL),
  ('delivery', 'Vinos Tintos', NULL, 'Escorihuela Gascón Malbec', '', 28000, NULL, true, 110, NULL),
  ('delivery', 'Vinos Tintos', NULL, 'Rutini Malbec', '', 45000, NULL, true, 111, NULL),
  ('delivery', 'Espumantes', NULL, 'Salentein Extra Brut', 'Espumante', 30000, NULL, true, 112, NULL),
  ('delivery', 'Espumantes', NULL, 'Salentein Brut Nature', 'Espumante', 30000, NULL, true, 113, NULL),
  ('delivery', 'Espumantes', NULL, 'Salentein Doux', 'Espumante', 30000, NULL, true, 114, NULL),
  ('delivery', 'Espumantes', NULL, 'Rutini Encuentro Brut Nature Pinot Noir', '', 55000, NULL, true, 115, NULL);

commit;
